### ISSUE TITLE
Plots on poster

### ISSUE THREAD

**Issue by Thapeachydude** [zuinelena3/BatChef#1]
Hi, 

we briefly chatted at the EMBO conference this weekend. I think it would be really helpful to share these insights with my lab. 
Is there a way that you could share the pictures used for your poster with me? (either as picture or code). 

Best, 
Marcel

**Comment by zuinelena3** [comment]
Hi Marcel, 

Sure! Here are the Figures used for my poster.
(a)
<img src="https://github.com/user-attachments/assets/eab87878-b3d3-4f53-9ed0-84e9da2892d5" alt="image" width="50%" height="auto">
    
(b)
<img src="https://github.com/user-attachments/assets/744744e3-279d-4b3b-8ef7-2344333ad4a7" alt="image" width="50%" height="auto">

Figure 1.(a) t-SNE plot of before and after batch effects correction. (b) Performance evaluation for each method: iLISI, and iASW (top), cLISI, and cASW (middle), and logarithm of Wasserstein distance metric (bottom).

(a)
<img src="https://github.com/user-attachments/assets/9c0b188d-42bc-47f4-b44d-4bbabfebbf38" alt="image" width="50%" height="auto">
(b)
<img src="https://github.com/user-attachments/assets/2e19fb96-135d-4b88-9626-a011087b5469" alt="image" width="50%" height="auto">

Figure 2. (a) log-average of Wasserstein distance across batch effect strength. (b) log-average of Wasserstein distance across sequencing depth for batch effects strength equal to 0.05 (top) and 0.1 (bottom).

For any questions or feedback,  please do not hesitate to contact me.
Best, 
Elena

**Comment by Thapeachydude** [comment]
Hi Elena, 

thank you so much!
